--local ok, packer = pcall(require, "plugins.packer")
--
--if not ok then
--	return false
--end
--
--local use = packer.use
--
--
--return packer.startup(function()
--	-- this is arranged on the basis of when a plugin starts
--	use("wbthomason/packer.nvim")
--	--use({
--	--	"ellisonleao/gruvbox.nvim",
--	--	config = function()
--	--		local colors = require("gruvbox.palette")
--	--		require("gruvbox").setup({
--	--			undercurl = true,
--	--			underline = true,
--	--			bold = true,
--	--			italic = true, -- will make italic comments and special strings
--	--			inverse = true, -- invert background for search, diffs, statuslines and errors
--	--			invert_selection = false,
--	--			invert_signs = false,
--	--			invert_tabline = false,
--	--			invert_intend_guides = false,
--	--			contrast = "hard", -- can be "hard" or "soft"
--	--			overrides = {
--	--				--WhichKey = { fg = colors.faded_blue, bg = colors.dark0, reverse = false },
--	--				WhichKeyFloat = { fg = colors.dark0, bg = colors.dark0, reverse = false },
--	--				WhichKeySeparator = { fg = colors.bright_purple, bg = colors.dark0_hard, reverse = false },
--	--			},
--	--		})
--	--		vim.cmd("colorscheme gruvbox")
--	--	end,
--	--	requires = {
--	--		"rktjmp/lush.nvim",
--	--	},
--	--})
--	use({
--		"kvrohit/substrata.nvim",
--		config = function()
--			vim.g.substrata_italic_comments = true
--			--vim.g.substrata_italic_keywords = true
--			--vim.g.substrata_italic_booleans = true
--			vim.g.substrata_italic_functions = true
--			--vim.g.substrata_italic_variables = true
--			vim.g.substata_variant = "default"
--			vim.cmd([[colorscheme substrata]])
--		end,
--	})
--	use("kyazdani42/nvim-web-devicons")
--
--	use({
--		"nvim-treesitter/nvim-treesitter",
--		config = function()
--			require("plugins.nvim-treesitter")
--		end,
--		run = ":TSUpdate",
--	})
--
--	use({ "p00f/nvim-ts-rainbow" })
--
--	use({
--		"lewis6991/gitsigns.nvim",
--		config = function()
--			require("plugins.gitsigns")
--		end,
--	})
--
--	use({
--		"max397574/better-escape.nvim",
--		config = function()
--			require("plugins.better-escape")
--		end,
--	})
--
--	use({
--		"lukas-reineke/indent-blankline.nvim",
--		config = function()
--			require("plugins.indent-blankline")
--		end,
--	})
--
--	use({
--		"norcalli/nvim-colorizer.lua",
--		config = function()
--			require("plugins.nvim-colorizer")
--		end,
--	})
--
--	use({
--		"nvim-telescope/telescope.nvim",
--		config = function()
--			require("plugins.telescope")
--		end,
--		requires = {
--			{
--				"nvim-lua/plenary.nvim",
--			},
--			{
--				"nvim-telescope/telescope-fzf-native.nvim",
--				run = "make",
--			},
--			{
--				"nvim-telescope/telescope-symbols.nvim",
--			},
--			{
--				"nvim-telescope/telescope-file-browser.nvim",
--			},
--		},
--	})
--
--	use({
--		"kyazdani42/nvim-tree.lua",
--		config = function()
--			require("plugins.nvim-tree")
--		end,
--		requires = {
--			"kyazdani42/nvim-web-devicons",
--		},
--	})
--
--	use({
--		"Pocco81/AutoSave.nvim",
--		config = function()
--			require("plugins.autosave")
--		end,
--	})
--
--	use({
--		"neovim/nvim-lspconfig",
--		config = function()
--			require("plugins.nvim-lspconfig")
--		end,
--		requires = {
--			"williamboman/nvim-lsp-installer",
--			"b0o/schemastore.nvim",
--			"folke/lua-dev.nvim",
--		},
--	})
--
--	use({
--		"jose-elias-alvarez/null-ls.nvim",
--		requires = {
--			"nvim-lua/plenary.nvim",
--		},
--	})
--
--	use({
--		"hrsh7th/nvim-cmp",
--		config = function()
--			require("plugins.nvim-cmp")
--		end,
--		requires = {
--			"L3MON4D3/LuaSnip",
--			"onsails/lspkind.nvim",
--			"hrsh7th/cmp-nvim-lsp",
--			"hrsh7th/cmp-buffer",
--			"hrsh7th/cmp-path",
--			"hrsh7th/cmp-cmdline",
--			"hrsh7th/nvim-cmp",
--		},
--	})
--
--	use({
--		"windwp/nvim-autopairs",
--		config = function()
--			require("plugins.nvim-autopairs")
--		end,
--	})
--
--	use({
--		"j-hui/fidget.nvim",
--		config = function()
--			require("plugins.fidget")
--		end,
--	})
--
--	use({
--		"RRethy/vim-illuminate",
--		config = function()
--			require("plugins.vim-illuminate")
--		end,
--	})
--
--	use({
--		"ellisonleao/glow.nvim",
--		config = function()
--			require("plugins.glow")
--		end,
--		ft = "markdown",
--	})
--
--	use({
--		"lukas-reineke/headlines.nvim",
--		config = function()
--			require("plugins.headlines")
--		end,
--	})
--
--	use({ "ixru/nvim-markdown", ft = "markdown" })
--
--	use({
--		"sunjon/shade.nvim",
--		config = function()
--			require("plugins.shade")
--		end,
--	})
--
--	use({
--		"folke/todo-comments.nvim",
--		requires = "nvim-lua/plenary.nvim",
--		config = function()
--			require("plugins.todo-comments")
--		end,
--	})
--
--	use({
--		"goolord/alpha-nvim",
--		requires = "kyazdani42/nvim-web-devicons",
--		config = function()
--			require("plugins.alpha-nvim")
--		end,
--	})
--
--	use({
--		"folke/which-key.nvim",
--		config = function()
--			require("plugins.which-key")
--		end,
--	})
--
--	use({
--		"nvim-neorg/neorg",
--		config = function()
--			require("plugins.neorg")
--		end,
--		requires = {
--			"nvim-lua/plenary.nvim",
--			"nvim-treesitter/nvim-treesitter",
--		},
--	})
--
--	use({
--		"folke/twilight.nvim",
--		config = function()
--			require("plugins.twilight")
--		end,
--	})
--
--	use({
--		"folke/zen-mode.nvim",
--		config = function()
--			require("plugins.zen-mode")
--		end,
--	})
--
--	use({
--		"NTBBloodbath/rest.nvim",
--		config = function()
--			require("plugins.rest")
--		end,
--	})
--end)
--