require("plugins.autosave")
require("plugins.better-escape")
require("plugins.fidget")
require("plugins.gitsigns")
-- require("plugins.glow")
-- require("plugins.headlines")
require("plugins.indent-blankline")
require("plugins.neorg")
require("plugins.nvim-autopairs")
require("plugins.nvim-cmp")
require("plugins.nvim-colorizer")
-- require("plugins.nvim-dap")
-- require("plugins.nvim-lspconfig")
require("plugins.nvim-tree")
require("plugins.nvim-treesitter")
--require("plugins.shade")
require("plugins.rest")
require("plugins.telescope")
require("plugins.todo-comments")
require("plugins.twilight")
require("plugins.vim-illuminate")
require("plugins.which-key")
require("plugins.zen-mode")