require("conform").setup({
	formatters_by_ft = {
		javascript = { "prettierd", "prettier" },
		json = { "jq" },
		just = { "just" },
		html = { "djlint" },
		htmlangular = { "prettierd" },
		htmldjango = { "djlint" },
		lua = { "stylua" },
		markdown = { "injected" },
		nix = { "nixfmt" },
		python = { "isort", "black" },
		sh = { "shellcheck" },
		toml = { "taplo" },
		typescript = { "prettierd", "prettier" },
		typescriptreact = { "prettierd", "prettier" },
		yaml = { "yamlfmt" },
		["*"] = { "trim_whitespace" },
	},
	-- log_level = vim.log.levels.TRACE,
})
