actual_server_url="$1"
actual_password="$2"
budget_sync_id="$3"
ollama_url="$4"
ollama_model="$5"
account_name="$6"
lookback_days="$7"
dry_run="$8"

export ACTUAL_SERVER_URL="$actual_server_url"
export ACTUAL_PASSWORD="$actual_password"
export BUDGET_SYNC_ID="$budget_sync_id"
export OLLAMA_URL="$ollama_url"
export OLLAMA_MODEL="$ollama_model"
export ACCOUNT_NAME="$account_name"
export LOOKBACK_DAYS="$lookback_days"
export DRY_RUN="$dry_run"

node --experimental-strip-types "$CATEGORIZER_APP/run.ts"
