# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/lucas/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source ~/.zplug/init.zsh

# Custom CLI commands
#
# add the good stuff
#
. ~/.zshsetopt
. ~/.zshaliases
. ~/.zshfunctions

# handy docker functions
. ~/.dockerfuncs

# Use ESC to edit the current command line:
# TODO: This should be in its own file
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\033' edit-command-line

# pyenv
# lazy load shims and autocompletion
#
pyenv() {
    eval "$( command pyenv init -)"
    eval "$( command pyenv virtualenv-init -)"
    pyenv "$@"
}

# Github Hub
#
eval "$(hub alias -s)"

# FZF
# cltrl-r and cltrl-t things
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Theme
#
# too slow...for now...
#zplug "denysdovhan/spaceship-zsh-theme", \
#    use:spaceship.zsh, \
#    from:github, \
#    as:theme
#
zplug "agkozak/agkozak-zsh-prompt", \
    use:agkozak-zsh-prompt.plugin.zsh, \
    from:github, \
    as:theme

zplug "zdharma/fast-syntax-highlighting", \
    from:github, \
    defer:2

# History
# 
zplug "zsh-users/zsh-history-substring-search"

# Prezto modules 
#
zplug "sorin-ionescu/prezto", \
    as:plugin, \
    use:init.zsh, \
    hook-build:"ln -s $ZPLUG_ROOT/repos/sorin-ionescu/prezto ${ZDOTDIR:-$HOME}/.zprezto"
zplug "modules/git", from:prezto
zplug "modules/homebrew", from:prezto
zplug "modules/osx", \
    from:prezto, \
    lazy:true
zplug "modules/utility", \
    from:prezto, \
    lazy:true

# NVM (node version manager)
#
export NVM_LAZY_LOAD=true
zplug "lukechilds/zsh-nvm"

# K8 & Helm
#
zplug "plugins/kubectl", \
    from:oh-my-zsh, \
    lazy:true
zplug "plugins/helm", \
    from:oh-my-zsh, \
    lazy:true

# zsh site-functions
# awless and kops
#
# zplug "/usr/local/share/zsh/site-functions", from:local, use:"_{awless,kops}", defer:2

# gcloud
#
if [ -d /usr/local/Caskroom/google-cloud-sdk ]; then
    source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
    source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
fi

# httpstat
#
zplug "b4b4r07/httpstat", \
    as:command, \
    use:'(*).sh', \
    rename-to:'$1', \
    lazy:true

# testssl.sh
# 
zplug "drwetter/testssl.sh", \
    as:command, \
    use:'(*).sh', \
    rename-to:'$1', \
    lazy:true

# zplug inception?
#
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Then, source plugins and add commands to $PATH
if [ "$ZPLUG_DEBUG" = true ]; then
    zplug load --verbose
else
    zplug load
fi
