# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/lucas/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source ~/.zplug/init.zsh

# Custom CLI commands
#
# add the good stuff
#
. ~/.zshsetopt
. ~/.zshaliases
. ~/.zshfunctions

# Github Hub
#
eval "$(hub alias -s)"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Theme
#
zplug "denysdovhan/spaceship-zsh-theme", \
    use:spaceship.zsh, \
    from:github, \
    as:theme

zplug "zdharma/fast-syntax-highlighting", defer:2

# History
# 
zplug "zsh-users/zsh-history-substring-search"
zplug "b4b4r07/zsh-history"

# Prezto modules I like to use 
#
zplug "modules/git", from:prezto
zplug "modules/homebrew", from:prezto
zplug "modules/osx", from:prezto
zplug "modules/utility", from:prezto

# Alias reminder
#
# NOTE: dont use this causes regex errors
# zplug "jedahan/ripz"

# NVM (node version manager)
zplug "creationix/nvm", use:nvm.sh

# Dropbox-cli
#
zplug "andreafabrizi/Dropbox-Uploader", \
    as:command, \
    use:'(*).sh', \
    rename-to:'$1'

zplug "b4b4r07/httpstat", \
    as:command, \
    use:'(*).sh', \
    rename-to:'$1'

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/lucas/repos/moneypenny/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/lucas/repos/moneypenny/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/lucas/repos/moneypenny/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/lucas/repos/moneypenny/node_modules/tabtab/.completions/sls.zsh