name: Update Flake Inputs
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}
        fetch-depth: 1

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty

    - name: Update Lockfile
      uses: DeterminateSystems/update-flake-lock@main
      id: update
      with:
        pr-title: ':package:(flake): bump'
        commit-msg: ':package:(flake): bump'
        token: ${{ secrets.ACTIONS_TOKEN }}

    - name: Merge Changes
      run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
